config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: [:create, :destroy] do
    resources :items, except: [:new, :edit, :show]
  end

  root "items#index"

end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :list, class_name: "List", foreign_key: "list_id"

  validates :name, presence: true

end

app/models/list.rb
class List < ActiveRecord::Base

  validates :name, presence: true
  validates_uniqueness_of :name, on: :create, message: "must be unique"

  has_many :items , dependent: :destroy

  def done_items
    items.where(done: true).order("updated_at DESC")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
def index
  @todo   = Item.where(:done => false)
  @item   = Item.new
  @lists  = List.all
  @list   = List.new

  respond_to do |format|
    format.html
    format.json do
      render :json => {:items => Item.all.map(&:to_json) }
    end
  end
end

def create
  @list = List.find(params[:list_id])
  raw_params = params[:item].is_a?(String) ? JSON.parse(params[:item]) : params[:item]
  item_params = ActionController::Parameters.new(raw_params)
  @item = @list.items.new(item_params.permit(:name))
  if @item.save
    status = "success"
    flash[:notice] = "Your item was created."
  else
    status = "failure"
    flash[:alert] = "There was an error creating your item."
  end
  respond_to do |format|
    format.html do
      redirect_to(list_items_url(@list))
    end
    format.json do
      render :json => {:status => status, :item => @item.to_json}
    end
  end
end

def update
  @list = List.find(params[:list_id])
  @item = @list.items.find(params[:id])

  respond_to do |format|
    if @item.update_attributes(item_attributes)
      format.html { redirect_to( list_items_url(@list), :notice => 'item was successfully updated.') }
    else
      format.html { render :action => "edit" }
    end
  end
end

def destroy
  @list = List.find(params[:list_id])
  @item = Item.find(params[:id])
  @item.destroy

  respond_to do |format|
    format.html { redirect_to(list_items_url(@list)) }
  end
end

private

def item_attributes
  params.require(:item).permit(:name, :done, :list_id)
end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def create
    @list = List.new(params.require(:list).permit(:name))
    if @list.save
      flash[:notice] = "Your list was created"
    else
      flash[:alert] = "There was an error creating your list."
    end
    redirect_to(list_items_url(@list))
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to(root_url) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>

    <%= f.input :name %><br />

    <%= f.input :done , :as => :hidden,  :input_html => {:value => false }%>


    <%= f.button :submit %>

<% end %>

app/views/items/_todo_item.html.erb
<%= simple_form_for(@todo) do |f| %>

    <li>
      <%= f.input :done , :label => false %>
      <%= @item.name %>
      <%= link_to 'X', @todo, :confirm => 'Are you sure?', :method => :delete %>
      <%= f.button :submit , :id => 'item_' + @todo.id.to_s %>
    </li>
<% end %>

app/views/items/index.html.erb
<div id='tabs'>
  <ul>
    <% @count = 1%>
    <% @lists.each do |list| %>
        <li>
          <a href="<%= '#' + 'tabs-' + @count.to_s %>"><%= list.name.capitalize %></a>
        </li>
        <% @count += 1%>
    <% end %>
    <li>
      <a href="#tabs-new-list">Add List +</a>
    </li>
  </ul>


  <% @count = 1%>
  <% @lists.each do |list| %>

      <div id='tabs-<%= @count %>' class="tab">

        <div class="new-item">
          <%= simple_form_for(@item, :url => list_items_url(list)) do |f| %>

              <%= f.input :done , :as => :hidden,  :input_html => {:value => false }%>
              <%= f.input :list_id , :as => :hidden,   :input_html => {:value => list.id }%>

              <div class="split-fields">
                <div class="field">
                  <%= f.input :name , :label => false, :placeholder => "Enter a new item" %>
                </div>
                <div class="button">
                  <%= f.button :submit,  "Add Item" %>
                </div>
              </div>
          <% end %>
        </div>

        <% unless list.items.empty? %>
            <ul  class="items pending-items">
              <% list.items.each do |item| %>

                  <% unless item.done %>
                      <%= simple_form_for(item, :url => list_item_url(list, item)) do |f| %>

                          <li>
                            <%= raw auto_link( h(item.name), :html => { :target => '_blank' }) %>
                            <%= link_to 'Delete', list_item_url(list, item), :confirm => 'Are you sure?', :method => :delete %>
                          </li>

                      <% end %>
                  <% end %>
              <% end %>
            </ul>
        <% end %>

        <% unless list.done_items.empty? %>
            <ul class="items finished-items">
              <% list.done_items.each do |item| %>
                  <li class="finished">
                    <%= raw auto_link( h(item.name), :html => { :target => '_blank' }) %>
                    <p class="delete-item">
                      <%= link_to 'Delete', list_item_url(list, item), :confirm => 'Are you sure?', :method => :delete %>
                    </p>
                  </li>
              <% end %>
            </ul>
        <% end %>

        <p class="delete-list">
          <%= link_to 'Delete this list', list, :confirm => 'Are you sure?', :method => :delete %>
        </p>
      </div>
      <% @count += 1%>

  <%end%>


  <div id="tabs-new-list">
    <h2>Add a New Item List</h2>
    <%= render :partial => '/lists/form' %>
  </div>


</div>


<% if listid = params[:list_id] %>
    <% prevlist = List.find listid %>
    <% tabindex = @lists.index(prevlist) %>
<% end %>


<script>
  $('.box').click(function(event) {
    $(this).parent().next().click();
  });

  $(function() {
    var opts = {};
    <% if params[:list_id] %>
    opts.selected = <%= tabindex %>
        <% end %>
        $( "#tabs" ).tabs(opts);
  });
</script>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Done:</b>
  <%= @item.done %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping List</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="all">
  <div id="header">
    <h1><span class="intro">Shopping List</span></h1>
  </div>
  <div id="content">
    <% if alerted = alert %>
        <p id="alert"><%= alerted %></p>
    <% end %>
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>

    <div class="split-fields">
      <div class="field">
        <%= f.input :name, :placeholder => "Name", :label => false %>
      </div>
      <div class="button">
        <%= f.button :submit, "Add List" %>
      </div>
    </div>
<% end %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>